name: hamster
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0
  path_provider: 2.1.2
  permission_handler: ^11.3.0
  path: ^1.8.0
  crypto: ^3.0.3
  floor: ^1.4.2
  build_runner: ^2.1.2
  device_info: ^2.0.0
  ffmpeg_kit_flutter: 6.0.3-LTS
  android_intent: ^2.0.2
  app_settings: ^4.0.0
  flutter_config: ^2.0.2
  uuid: ^3.0.4
  flutter_dotenv: ^5.1.0
  # 播放器
  video_player: ^2.4.0
  # 屏幕旋转
  auto_orientation: ^2.2.1
  # 亮度和音量调节
  brightness_volume: ^1.0.3
  # 状态管理
  get: ^4.6.6
  external_path: ^1.0.3
  chewie: 1.7.5
  image_picker: ^0.8.4+4
  provider: ^6.0.5
  file_picker: ^8.0.0+1
  video_thumbnail: ^0.5.3
  pull_to_refresh: ^2.0.0
#  wakelock: ^0.6.2
  wakelock_plus: ^1.1.6
  video_compress: ^3.1.2
  # 日志打印
  logger: ^2.3.0
#  drift: ^2.4.2
  sqlite3_flutter_libs: ^0.5.0
  cupertino_icons: ^1.0.6
  bruno: ^3.4.3
  tdesign_flutter: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  path_provider: 2.1.2
  permission_handler: ^11.3.0
  sqflite: ^2.0.0
  crypto: ^3.0.3
  floor_generator: ^1.3.0
  build_runner: ^2.1.2
  device_info: ^2.0.0
  ffmpeg_kit_flutter: 6.0.3-LTS
  android_intent: ^2.0.2
  app_settings: ^4.0.0
  flutter_config: ^2.0.2
  uuid: ^3.0.4
  flutter_dotenv: ^5.1.0
  provider: ^6.0.5
#  drift_dev: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/image/image_1.png
    - assets/image/image_2.png
    - assets/image/no-pictures.png
    - .env